# /*************************************************************************************************
# * Copyright 2022 Theai, Inc. (DBA Inworld)
# *
# * Use of this source code is governed by the Inworld.ai Software Development Kit License Agreement
# * that can be found in the LICENSE.md file or at https://www.inworld.ai/sdk-license
# *************************************************************************************************/

name: build-Unity

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'


jobs:
  build-Unity:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: git-update-dependecies
      run: git submodule update --init --recursive | Write-Host
    - name: build-Unity-DLL
      shell: pwsh
      run: |
          Start-Process -FilePath "win-gen-unity.bat" " > GenLog.txt" -Wait -NoNewWindow -PassThru 
          cat GenLog.txt
          if (Select-String -Path GenLog.txt -Pattern "Generating done" -SimpleMatch -Quiet)
          {
            exit 0
          }
          else
            exit 1

         
